development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: playbook_development
  pool:     5
  username: postgres
  password:

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: playbook_test
  pool:     5
  username: postgres
  password:

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: playbook_production
  pool:     5
  username: postgres
  password: postgres
